test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digital_ocean:
  service: S3
  endpoint: https://sfo3.digitaloceanspaces.com
  access_key_id: <%= Rails.application.credentials.dig(:digital_ocean, :access_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digital_ocean, :secret) %>
  bucket: nuku-blog-<%= ['test', 'development'].include?(Rails.env) ? 'development' : 'production'  %>
  region: unused

digital_ocean_production:
  service: S3
  endpoint: https://sfo3.digitaloceanspaces.com
  access_key_id: <%= Rails.application.credentials.dig(:digital_ocean, :access_key) %>
  secret_access_key: <%= Rails.application.credentials.dig(:digital_ocean, :secret) %>
  bucket: nuku-blog-production
  region: unused
